security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
  providers:
    webcams:
      memory:
        users:
          alain:
            password: '%env(ALAIN_PASSWORD)%'
            roles: ROLE_USER
          john:
            password: '%env(JOHN_PASSWORD)%'
            roles: ROLE_USER
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    secured:
      pattern: ^/
      provider: webcams
      remember_me:
        secret: '%kernel.secret%'
        lifetime: 315360000
        always_remember_me: true
      form_login:
        login_path: app_login
        check_path: app_login
        enable_csrf: true
        default_target_path: home
      logout:
        path: app_logout
        target: app_login
  access_control:
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: ROLE_USER }
