security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
  providers:
    webcams:
      memory:
        users:
          alain:
            password: '%env(ALAIN_PASSWORD)%'
            roles: ROLE_USER
          john:
            password: '%env(JOHN_PASSWORD)%'
            roles: ROLE_USER
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    secured:
      pattern: ^/
      provider: webcams
      http_basic: ~
      remember_me:
        secret: '%kernel.secret%'
        lifetime: 315360000
        always_remember_me: true
  access_control:
    - { path: ^/, roles: ROLE_USER }
